const gulp = require('gulp')
const sass = require('gulp-sass')
const autoprefixer = require('gulp-autoprefixer');
const terser = require('gulp-terser');
const browserSync = require('browser-sync');
const htmlmin = require('gulp-htmlmin');
const concat  = require('gulp-concat')
const cssnano = require('gulp-cssnano')
const clean = require('gulp-clean')

// Limpa a pasta dist
// --------------------------------------------------
gulp.task('clean', function(){
    return gulp.src('dist')
        .pipe(clean());
})

// Performance do html
// --------------------------------------------------
gulp.task('minifyhtml', function() {
    return gulp.src('./src/*.html')
      .pipe(htmlmin({
        removeComments: true,
        collapseWhitespace: true,
        includeAutoGeneratedTags: true
      }))
      .pipe(gulp.dest('./dist/'))
  });

// Pega todos os arquivos .scss e faz o tratamento, jogando ele em dist/css
// --------------------------------------------------
gulp.task('sass', function() {
    return gulp.src('./src/sass/**/*.scss') 
        .pipe(sass()) //trata o scss para css
        .pipe(autoprefixer()) //adiciona prefixos em regras de css baseado no Can I Use
        .pipe(cssnano()) // otimiza o css
        .pipe(gulp.dest('./dist/css/')); 
})

// Faz o tratamento performático nos arquivos de javascript
// --------------------------------------------------
gulp.task('buildjs', function() {
    return gulp.src('./src/js/**/*.js')
        .pipe(concat('app.min.js')) //concatena tudo neste arquivo novo
        .pipe(terser()) //minifica :3
        .pipe(gulp.dest('./dist/js/'))
})

// Copia o assets pra dist
// --------------------------------------------------
gulp.task('copy', function() {
    return gulp.src([
            './src/assets/**/*'])
        .pipe(gulp.dest('./dist/assets'))
})

// Pastinha dist
// --------------------------------------------------
gulp.task('dist', gulp.series('copy', gulp.parallel('minifyhtml', 'sass', 'buildjs')), function(done) {
    done()
})

// Servidor lindinho que dá reload :3
// --------------------------------------------------
gulp.task('server',  function() {
    browserSync.init({
        server: {
            baseDir: 'dist'
        }
    })

    gulp.watch('./*/dist/**/*').on('change', browserSync.reload);
})

// Vai ficar escutando os eventos <3
// --------------------------------------------------
gulp.task('listen', function() {
    gulp.watch('./src/js/**/*', gulp.series('buildjs'));
    gulp.watch('./src/sass/**/*.scss', gulp.series('sass')); 
    gulp.watch('./src/*.html', gulp.series('minifyhtml')); 
});